### ISSUE TITLE
TensorFlow Model training

### ISSUE THREAD

**Issue by dainius-kavoliunas** [Esri/raster-deep-learning#10]
Hi,
Can you share a workflow how you trained tree detection or land classification model?
Thanks!

**Comment by sang4758** [comment]
Hi @dainius-kavoliunas  , You can train using a no. different Deep Learning frameworks whether  its Tensorflow , PyTorch, Keras, CNTK. If you are interested in Tensorflow , you can use the Tensorflow Object Detection API to train this. Here is the link to the github repo... https://github.com/tensorflow/models/tree/master/research/object_detection
There are some tutorials on this online... Here is one...https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10
If you are not specific about the framwork , ArcGIS has built in learn modules using PyTorch in the ArcGIS API for Python that you can use for training... Here is the reference.. https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.learn ... A sample notebook is here ... https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/detecting_swimming_pools_using_satellite_image_and_deep_learning.ipynb . Hope this helps.
