### ISSUE TITLE
Install from env_setup.bat missing cython

### ISSUE THREAD

**Issue by tim-mcg** [Esri/raster-deep-learning#13]
When installing the environment using the provided env_setup.bat file an error is shown :

> object-detection 0.1 requires Cython>=0.28.1, which is not installed.
> mkl-random 1.0.1 requires cython, which is not installed.
> mkl-fft 1.0.4 requires cython, which is not installed.
> cftime 1.0.0b1 requires cython, which is not installed.

This is easily fixed by modifying the following line in the batch file from:

> CALL "%SCRIPTS_DIR%conda.exe" install -c anaconda %TF_PACKAGE% keras scikit-image --yes

To:

> CALL "%SCRIPTS_DIR%conda.exe" install -c anaconda cython %TF_PACKAGE% keras scikit-image --yes

**Comment by lingtangraster** [comment]
@tim-mcg 
Thanks for the good suggestion. This requirement is newly introduced after conda install upgrades to TensorFlow 1.13. We can certainly make the suggested change. 
However, as you can see, it is unrealistic to address all the Python libraries dependency issues, especially if it is also related to the users' specific Python environments. The users are responsible to setup a workable Python Env. for the third party deep learning framework APIs, such as TensorFlow. The environment setup batch file (env_setup.bat) is served for general use purpose, which provide a good start for the users.
