### ISSUE TITLE
OSError: Cannot identify image file

### ISSUE THREAD

**Issue by Pratyush1991** [Esri/raster-deep-learning#28]
Hello,

Currently, I am trying to train the U-Net Model for the classification of land cover. The input image is a 16-bit unsigned integer Tiff file of 4 bands (Blue, Green, Red and NIR). The training data are in vector format which I converted to unsigned int 8 bit Tiff as well as Exported the Traning data for Deep Learning as "Classified Tiles" per Instructions shown in the link. [(Extracting Building Footprint from Drone Data)](https://developers.arcgis.com/python/sample-notebooks/extracting-building-footprints-from-drone-data/). But I'm stuck in data preparation it gives an error as "Cannot Identify Image File". 
Could you suggest how can I resolve this issue?

![Error](https://user-images.githubusercontent.com/28738918/74963663-b0dcef80-5444-11ea-8780-49b56b2231cf.PNG)

**Comment by sang4758** [comment]
Hi, 
The training works on 8 bit 3 band data. You would need to apply a  Extract Band function/tool to the input image to make it 3 bands before exporting and training.

**Comment by Pratyush1991** [comment]
Thank you. It did work after I converted them to 8 bit.

**Comment by abinprajapati** [comment]
I get same error: OSError: Cannot identify image file.
I have converted to 8 bit but this couldnt resolve this problem. Can you help me in this regard.
