### ISSUE TITLE
Missing *h5 model

### ISSUE THREAD

**Issue by AnastasiyaTi** [Esri/raster-deep-learning#29]
In the example  HouseDamageClassifier *emd file has link for  the model  "ModelFile":".\\Damage_Classification_Model_V7.h5". 
Unfortunately, this particular *h5 model  is missed in the pack of  files. So this example cant be executed

**Comment by lingtangraster** [comment]
@AnastasiyaTi Thanks to point it out, the link to download is here: https://www.arcgis.com/home/item.html?id=8549fbf2be404e678934d224f9804298

I will add the link to the example page: https://github.com/Esri/raster-deep-learning/tree/master/examples/keras/object_classification

**Comment by lingtangraster** [comment]
Issue fixed.
