### ISSUE TITLE
Download sample images and sample trained deep learning models

### ISSUE THREAD

**Issue by bhammersley1995** [Esri/raster-deep-learning#8]
When will the links for the sample images and trained deep learning models be added?

**Comment by dengding** [comment]
Here's a learn lesson to get started: https://github.com/Esri/raster-deep-learning/wiki/Learning-Resources
with instructions for getting the data and model. This is just one example for Detecting Objects using a tensorflow model. We will upload more examples in the near future.

**Comment by lingtangraster** [comment]
@bhammersley1995 
The downloading links for the sample images and trained deep learning model are added to the repo's landing page. 
I also include the link here for your convenience:  https://www.arcgis.com/apps/MinimalGallery/index.html?appid=99c39f7512d54881bc365583c76c7da6

**Comment by lingtangraster** [comment]
Resolved issue and close.
